### ISSUE TITLE
EolMap is not a map

### ISSUE THREAD

**Issue by micfort** [eclipse/epsilon#124]
so a very interesting issue showed up today for me with the following code:
```
var test = Map{"a" = 1, "b" = 2};
test["a"].println();
```

I got the following error `EolMap {a=1, b=2} is not a collection or a map.`
So the error is definitely wrong, because EolMap is a map, but the question is more is the following syntax allowed: `test["a"]` ?

**Comment by kolovos** [comment]
Thanks for reporting this issue. It is a bug and it will be fixed in 2.6.

**Comment by kolovos** [comment]
This now works as expected. Also, item selector expressions can now be used to set/put values in collections/maps as shown in the [tests](https://github.com/eclipse/epsilon/blob/main/tests/org.eclipse.epsilon.eol.engine.test.acceptance/src/org/eclipse/epsilon/eol/engine/test/acceptance/ItemSelectorTests.eol).
