### ISSUE TITLE
Embedding non-XML views in Picto

### ISSUE THREAD

**Issue by kolovos** [eclipse/epsilon#14]
Trying to embed views which are not valid XML in other Picto views fails at the moment as reported in this [forum post](https://www.eclipse.org/forums/index.php/t/1112039/). A minimal example with a standalone Picto file and two custom HTML views follows.

```xml
<!--example.picto-->
<?nsuri picto?>
<picto standalone="true">
	<view path="Root, View1" format="html" source="view1.html"/>
	<view path="Root, View2" format="html" source="view2.html"/>
</picto>
```

```html
<!--view1.html-->
View 1
```

```html
<!--view2.html-->
<html>
<h1>View 2</h1>
<picto-view path="Root, View1"/>
</html>
```

Trying to render `Root/View2` produces a `Content is not allowed in prolog.` error message in Picto because `view1.html` is not valid XML.

To fix this we could try to parse the content of the view to embed as XML and if this fails, put it in an `iframe` instead.

It would also be nice to support a custom `iframe` attribute in `<picto-view>` elements to allow the user to force an iframe (e.g. if the other view is XHTML but the user doesn’t want its CSS/JavaScript to mess up the host page’s style/functionality).

**Comment by alfonsodelavega** [comment]
I have found a solution that also solves an extra problem with iframes: detecting the proper height and width of the contents.

Using the [iFrame Resizer](https://davidjbradshaw.github.io/iframe-resizer/) library, it's possible to fix iframe weight at 100% and then determine the height of the contents after rendering ([example](https://davidjbradshaw.com/iframe-resizer/example/)).

This library requires adding a js file to the upper html, and another js file to the inner one (i.e. the one contained in the iframe). Would this last part be much of a hussle?
