### ISSUE TITLE
Bug: workflow ForTask will execute children one time even if there are no matching files

### ISSUE THREAD

**Issue by Arkaedan** [eclipse/epsilon#16]
### Bug
The `epsilon.for` Ant task will execute once with the `it` property set to empty string when the fileset has no matching files. 
### Desired behaviour
The `epsilon.for` Ant task should not execute if the fileset has no matching files
### Cause
If the fileset has no matching files, the task's `getFiles()` method returns a string array with one element, an empty string, instead of return an empty array

**Comment by kolovos** [comment]
Thanks for taking the time to report this issue and submit a PR! Fixed in https://github.com/eclipse/epsilon/commit/68f9570fd9a400e54ba6aa98e6fbe6392be01e40.
