### ISSUE TITLE
Outdated PlantUML version in target platform / Orbits

### ISSUE THREAD

**Issue by alfonsodelavega** [eclipse/epsilon#29]
The PlantUML version available in Eclipse Orbits is outdated (1.2019) and lacks the recent improvements in PlantUML rendering included by the maintainers (e.g. see [this](https://plantuml.com/class-diagram)). The same PlantUML version is maintained in more recent Orbits than the one we have in the target platform (such as the latest [2022-12](https://download.eclipse.org/tools/orbit/downloads/drops/R20221123021534/) one)

Does anyone know what is the proper way to upgrade the Orbit version? I'm currently using the [update site](https://github.com/hallvard/plantuml) PlantUML authors provide for their Eclipse plugins in a local target platform, and so far it works fine.

I think this relates to Epsilon because we're probably the only ones using that feature (seems that @SMadani added it).

**Comment by agarciadom** [comment]
Shouldn't it go through some type of IP check? I know IPZilla is no more, but it might not be as easy as just pushing the change.

**Comment by kolovos** [comment]
I see that @SMadani submitted an [IP check request](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24189) for plantuml-1.2022.6, which was approved in late November.

**Comment by arcanefoam** [comment]
I meant the technical part. Yes, the PR has to come with an IP check.

**Comment by alfonsodelavega** [comment]
PlantUML version updated to 1.2023.11.
