### ISSUE TITLE
Some Picto HTML views appear Blank in Windows 10 instances

### ISSUE THREAD

**Issue by alfonsodelavega** [eclipse/epsilon#47]
I have found an issue (and a potential solution) with Picto in Windows that I want to test further.

To reproduce:

1. In an Eclipse instance with Epsilon installed, import `org.eclipse.epsilon.examples.picto.ecore` , open any `.ecore` file and the Picto window
2. A visualisation should appear, if the `Stats` view is selected in the tree, it might appear blank
3. (same with `3D inheritance`)

The current solution I found: add `-Dorg.eclipse.swt.browser.DefaultType=edge` to the `eclipse.ini` file of your Eclipse instance.

Another solution could be to detect if Windows is the OS in use and then instantiate the Browser in Picto with the `SWT.EDGE` option (similar `SWT.WEBKIT` exists for Os X, and other deprecated options as well). Info: https://github.com/eclipse-platform/eclipse.platform.swt/blob/19c5bc83ae72e7d31767a1b4575511d148975794/bundles/org.eclipse.swt/Eclipse%20SWT/common/org/eclipse/swt/SWT.java#L2572

**Comment by kolovos** [comment]
Archi seems to also be setting the browser to Edge on Windows by default, but this can be changed through a preference: https://github.com/archimatetool/archi/blob/278259bb117c64f347e120844a017384c6de83ab/com.archimatetool.editor/src/com/archimatetool/editor/ArchiWorkbenchAdvisor.java#L55
