### ISSUE TITLE
ETL Special Assignment Operator semantics not respected by imported EOL scripts

### ISSUE THREAD

**Issue by arcanefoam** [eclipse/epsilon#53]
**Description**

When importing an EOL script into ETL, the Special Assignment Operator semantics are not respected when executing the code in the EOL script.

**Example**
```
// ETL
import "helper.eol"
rule AB
  transform a:A
  to b:B {
  b.ref = createC(a); 
} 
----

// helper.eol
operation createC(a:A) return C {
  var c = new C;
  c.other ::= a;
  return a;
}
```
**Current Behavior**

The statement `c.other ::= a`, will try to assign `a` to `c.other`, resulting in a cast error.

**Expected Behavior**
The statement `c.other ::= a`, will assign `a`'s equivalent to `c.other`.

**Comment by kolovos** [comment]
Thanks for reporting this Horacio. I've attached a [minimal working example](https://github.com/eclipse/epsilon/files/12683135/issue-53-minimal-example.zip) that demonstrates the issue.

**Comment by kolovos** [comment]
Until this gets fixed, you can use `.equivalent()` instead of `::=` as a workaround, i.e. `c.other = a.equivalent()` in your example.

**Comment by kolovos** [comment]
Fixed in https://github.com/eclipse/epsilon/commit/f5fc8db2d6c907b0875ef8f9e2b2a41a40a1c809.
