### ISSUE TITLE
Please update the setup to use the appropriate GitHub URIs.

### ISSUE THREAD

**Issue by merks** [eclipse/epsilon#70]
The builds are failing which made me notice:

https://ci.eclipse.org/oomph/job/setup-archiver/lastBuild/

I expect these git clone tasks don't work properly either:

![image](https://github.com/eclipse/epsilon/assets/208716/a0927931-4dcb-4a2f-adb8-652f90201649)

They should look more like this:

![image](https://github.com/eclipse/epsilon/assets/208716/4651acbd-032c-41c2-aeee-ff5278c5bcbc)

Generally it's a good idea to change the id of each git clone tasks so that the old/out-dated recorded values in the user.setup are not reused.   Make sure you change all the reference to that ID via induced variable if you do that.

**Comment by agarciadom** [comment]
I updated the `epsilonDev.setup` file to use Github URLs, and also fixed a few other things (activating the right update site, and setting up the workspaces). Could you confirm it works now from the Oomph CI?

**Comment by merks** [comment]
The build at the link runs every 15 minutes. It still fails with this image reference 

> FAILED to load https://git.eclipse.org/c/www.eclipse.org/epsilon.git/plain/mkdocs/docs/assets/images/epsilon-eclipse-installer.png

Search for that.  In the editor ctrl-F works too.

**Comment by agarciadom** [comment]
I cannot find that string anymore in our epsilonDev.setup file. The CI build log says this:

```
Mirroring https://raw.githubusercontent.com/eclipse/epsilon/main/releng/org.eclipse.epsilon.releng/epsilonDev.setup
```

If I load [that URL](https://raw.githubusercontent.com/eclipse/epsilon/main/releng/org.eclipse.epsilon.releng/epsilonDev.setup), our only reference to the `epsilon-eclipse-installer.png` file now has the new Github-based URL:

```
      <value>https://eclipse.dev/epsilon/assets/images/epsilon-eclipse-installer.png</value>
```

You can check this in our repository:

https://github.com/eclipse/epsilon/blob/c1ef36508c4beead5d0d0d3e17b2818911245b19/releng/org.eclipse.epsilon.releng/epsilonDev.setup#L22

Could there be some kind of caching on the CI side which is causing this issue to persist even after we fixed our file?

**Comment by merks** [comment]
I see that value is here:

https://github.com/eclipse/epsilon/blob/a94d632ec75dbac156abded06a48c88e5230dbe2/releng/org.eclipse.epsilon.releng/epsilonUse.setup#L22

**Comment by agarciadom** [comment]
Oh, I missed that file. I've just pushed a fix - hopefully the next CI build will complete.

**Comment by merks** [comment]
Yes, this build is clean and promoted the change:

https://ci.eclipse.org/oomph/job/setup-archiver/74396/

Thanks.  😄
