### ISSUE TITLE
PlainXML Model - dom.Element method implementations are internal

### ISSUE THREAD

**Issue by arcanefoam** [eclipse/epsilon#8]
As mentioned in the XML EMC [page](https://www.eclipse.org/epsilon/doc/articles/plain-xml/), all methods of the [org.w3c.dom.Element](https://docs.oracle.com/javase/7/docs/api/org/w3c/dom/Element.html) should be available to elements of the PlainXML model.

However, in latest versions of Java, the `ElementImpl'  class that is under `com.sun.org.apache.xerces.internal.dom` is no longer accesible via reflection. Thus, calls to any of the Element interface methods fails. The first case of this was reported in #5 (access to getTagName()), but further use has reveal the same issues when accessing `appendChild()`.  We imagine any other method calls will result in the same issue.

**Comment by kolovos** [comment]
I've pushed a [tweaked version](https://github.com/eclipse/epsilon/commit/14d2a3eb9f8424794cd897efb6c00e5d500e895d) of the content in the pull request to maintain compatibility with Java 8. All XML-related tests now pass with Java 17 without the `--add-exports` flag.

**Comment by arcanefoam** [comment]
Works as expected! Thanks.
