### ISSUE TITLE
Problems detected during plugin validation

### ISSUE THREAD

**Issue by kolovos** [eclipse/epsilon#85]
Trying to run a nested Eclipse instance with the latest version of our target platform produces several plugin validation issues (see below).

![image](https://github.com/eclipse/epsilon/assets/3584136/f9017c58-9b45-401a-951a-9c72c6c4a738)

**Comment by agarciadom** [comment]
I'm not getting any such errors, though. This is from c91e7e4e6d865f660ab2994c69085e3080fb07b2:

![image](https://github.com/eclipse/epsilon/assets/46504/c5d22338-4af9-4b87-8828-c2bee5521e22)

See my "Main" tab:

![image](https://github.com/eclipse/epsilon/assets/46504/693089d7-09a9-4608-a58a-664d62a0251b)

**Comment by agarciadom** [comment]
Just to be sure - can you double check you are using Java 17? I think recent versions of Eclipse require it.

**Comment by kolovos** [comment]
Apologies - this was due to some non-Epsilon projects I had forgotten to close in my workspace.
