### ISSUE TITLE
[Excel] Numeric cell value takes precedence over configured column datatype

### ISSUE THREAD

**Issue by agarciadom** [eclipse/epsilon#89]
Kostas and I were today puzzling over some odd behaviour while using the Excel driver. We noticed that a column with numeric IDs (e.g. `123456`) was being parsed by the driver as having floating-point numbers, even though we had indicated in the `config.xml` that its datatype was `string`. We had to instead use `integer` as its `datatype`, so we'd get all digits properly and we could do appropriate ID matching.

Looking at the code in `ExcelRow`, it seems it checks the type detected by POI first, and then it checks the declared datatype:

https://github.com/eclipse/epsilon/blob/428c241941979819d7fe3d133d387cd306fe2e4e/plugins/org.eclipse.epsilon.emc.spreadsheets.excel/src/org/eclipse/epsilon/emc/spreadsheets/excel/ExcelRow.java#L38-L58

This means that even if someone says that a column should be treated as text, we'll still treat it as a numeric if POI considers it to be a numeric value. Is this the expected behaviour? I think it may confuse users if we do not honour their declared preference. On the other hand, I'm aware that by flipping the order of the checks (first declared datatype then POI type) we may be breaking some scripts, as the default datatype is actually `string`.

Any thoughts?

**Comment by kolovos** [comment]
I agree - the declared type should trump the auto-detected one.
